import { IChat } from '../types/chat';
import { IChallenge, IChallengeEvent } from '../types/challenge';
import { IGroup, IGroupPost } from '../types/group';
import { IJobListing } from '../types/job';
import { IPost } from '../types/post';
import { IShort } from '../types/short';
import { IStory } from '../types/user';

export const postsData: IPost[] = [
  {
    _id: '1',
    user: {
      _id: '1',
      username: 'leo_martin',
      fullName: 'Léo Martin',
      dp: 'https://random.imagecdn.app/500/200',
    },
    caption:
      'Soirée passée à déboguer une fuite mémoire dans une app Node.js. Trois heures de traque, un coupable : une closure oubliée dans un setInterval. 😅 Si vous aussi vous galérez avec la gestion mémoire en Node, je prépare un thread complet avec les outils que j’ai utilisés (heap snapshot, --inspect, Chrome DevTools). 🌅',
    image: 'https://random.imagecdn.app/1920/1081',
    likes: 129,
    comments: 5,
    commentsData: [
      {
        _id: 'c1',
        user: {
          _id: 'u2',
          fullName: 'Sarah Chen',
          dp: 'https://random.imagecdn.app/210/210',
        },
        text: 'Le classique ! Pense à toujours nettoyer tes listeners aussi.',
        likes: 16,
        reactions: ['fas fa-thumbs-up', 'fas fa-laugh'],
        createdAt: new Date(Date.now() - 7 * 3600000),
        replies: [
          {
            _id: 'c1r1',
            user: {
              _id: 'u3',
              fullName: 'Ryan Cooper',
              dp: 'https://random.imagecdn.app/211/211',
            },
            text: 'Totalement d’accord !',
            likes: 4,
            reactions: ['fas fa-thumbs-up'],
            createdAt: new Date(Date.now() - 6 * 3600000),
          },
        ],
      },
      {
        _id: 'c2',
        user: {
          _id: 'u4',
          fullName: 'Emily Carter',
          dp: 'https://random.imagecdn.app/212/212',
        },
        text: 'Hâte de voir le thread, c’est un sujet qui manque !',
        likes: 8,
        reactions: ['fas fa-heart'],
        createdAt: new Date(Date.now() - 5 * 3600000),
      },
      {
        _id: 'c3',
        user: {
          _id: 'u5',
          fullName: 'Tyler Brooks',
          dp: 'https://random.imagecdn.app/213/213',
        },
        text: 'J’ai eu exactement le même bug la semaine dernière 😂',
        likes: 12,
        reactions: ['fas fa-thumbs-up', 'fas fa-heart'],
        createdAt: new Date(Date.now() - 4 * 3600000),
      },
      {
        _id: 'c4',
        user: {
          _id: 'u6',
          fullName: 'Derek Morgan',
          dp: 'https://random.imagecdn.app/214/214',
        },
        text: 'Ce thread mérite plus de likes !',
        likes: 3,
        reactions: ['fas fa-thumbs-up'],
        createdAt: new Date(Date.now() - 2 * 3600000),
      },
      {
        _id: 'c5',
        user: {
          _id: 'u7',
          fullName: 'Jason Foster',
          dp: 'https://random.imagecdn.app/215/215',
        },
        text: 'Continue de poster ce genre de contenu.',
        likes: 6,
        reactions: ['fas fa-thumbs-up', 'fas fa-laugh'],
        createdAt: new Date(Date.now() - 1 * 3600000),
      },
    ],
    shares: 0,
    sharesData: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '2',
    user: {
      _id: '1',
      fullName: 'Léo Martin',
      username: 'leo_martin',
      dp: 'https://random.imagecdn.app/500/200',
    },
    caption:
      'Juste terminé un sprint de 3 jours sur un projet open-source. Trois jours de deep work, des revues de code honnêtes, et beaucoup de rires. C’est fou ce qu’on arrive à faire quand on se déconnecte du bruit et qu’on collabore vraiment. Déjà hâte de la prochaine itération. Merci à tous les contributeurs ! 🙏✨',
    image: 'https://random.imagecdn.app/1920/1070',
    likes: 798,
    comments: 52,
    commentsData: [
      {
        _id: 'c6',
        user: {
          _id: 'u8',
          fullName: 'Michael Campbell',
          dp: 'https://random.imagecdn.app/216/216',
        },
        text: 'C’est absolument énorme ! 🔥',
        likes: 45,
        reactions: ['fas fa-fire', 'fas fa-heart'],
        createdAt: new Date(Date.now() - 10 * 3600000),
        replies: [
          {
            _id: 'c6r1',
            user: {
              _id: 'u9',
              fullName: 'Marcus Henderson',
              dp: 'https://random.imagecdn.app/217/217',
            },
            text: 'Complètement d’accord avec ça !',
            likes: 9,
            reactions: ['fas fa-thumbs-up'],
            createdAt: new Date(Date.now() - 9 * 3600000),
          },
          {
            _id: 'c6r2',
            user: {
              _id: 'u10',
              fullName: 'Henry Kane',
              dp: 'https://random.imagecdn.app/218/218',
            },
            text: 'Pareil ! Je partage tout de suite.',
            likes: 5,
            reactions: ['fas fa-thumbs-up'],
            createdAt: new Date(Date.now() - 8 * 3600000),
          },
        ],
      },
      {
        _id: 'c7',
        user: {
          _id: 'u11',
          fullName: 'Russell Hansen',
          dp: 'https://random.imagecdn.app/219/219',
        },
        text: 'J’attendais ça. Trop content que tu l’aies posté.',
        likes: 22,
        reactions: ['fas fa-thumbs-up', 'fas fa-surprise'],
        createdAt: new Date(Date.now() - 8 * 3600000),
      },
      {
        _id: 'c8',
        user: {
          _id: 'u12',
          fullName: 'Nathan Hayes',
          dp: 'https://random.imagecdn.app/220/220',
        },
        text: 'La qualité du code est incroyable. 👌',
        likes: 31,
        reactions: ['fas fa-thumbs-up'],
        createdAt: new Date(Date.now() - 6 * 3600000),
        replies: [
          {
            _id: 'c8r1',
            user: {
              _id: 'u13',
              fullName: 'Kevin Andrews',
              dp: 'https://random.imagecdn.app/221/221',
            },
            text: 'On ne pouvait pas mieux dire !',
            likes: 7,
            reactions: ['fas fa-thumbs-up'],
            createdAt: new Date(Date.now() - 5 * 3600000),
          },
        ],
      },
      {
        _id: 'c9',
        user: {
          _id: 'u14',
          fullName: 'Scott Irving',
          dp: 'https://random.imagecdn.app/222/222',
        },
        text: 'Je partage à tous mes collègues devs.',
        likes: 14,
        reactions: ['fas fa-heart'],
        createdAt: new Date(Date.now() - 4 * 3600000),
      },
      {
        _id: 'c10',
        user: {
          _id: 'u15',
          fullName: 'Travis Ingram',
          dp: 'https://random.imagecdn.app/223/223',
        },
        text: 'Ça a illuminé ma journée ! Merci pour le partage.',
        likes: 19,
        reactions: ['fas fa-laugh', 'fas fa-heart'],
        createdAt: new Date(Date.now() - 2 * 3600000),
      },
    ],
    shares: 10,
    sharesData: [
      {
        _id: 's1',
        user: {
          _id: 'u30',
          fullName: 'Ethan Bishop',
          dp: 'https://random.imagecdn.app/230/230',
        },
        sharedAt: new Date(Date.now() - 5 * 86400000),
      },
      {
        _id: 's2',
        user: {
          _id: 'u31',
          fullName: 'Ryan Hale',
          dp: 'https://random.imagecdn.app/231/231',
        },
        sharedAt: new Date(Date.now() - 2 * 86400000),
      },
      {
        _id: 's3',
        user: {
          _id: 'u32',
          fullName: 'Aaron Hudson',
          dp: 'https://random.imagecdn.app/232/232',
        },
        caption: 'C’est exactement ce qu’il me fallait aujourd’hui !',
        sharedAt: new Date(Date.now() - 1 * 86400000),
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '3',
    user: {
      _id: '1',
      fullName: 'Léo Martin',
      username: 'leo_martin',
      dp: 'https://random.imagecdn.app/500/200',
    },
    caption:
      'J’ai commencé à apprendre Rust ce mois-ci et honnêtement c’est humiliant. Il y a quelque chose de puissant à être débutant à nouveau — la curiosité, les petites victoires, la frustration inévitable avec le borrow checker. La progression ne s’arrête jamais si tu continues d’avancer. Lâchez un 💪 si vous apprenez aussi quelque chose de nouveau en ce moment !',
    image: 'https://random.imagecdn.app/1920/1060',
    likes: 456,
    comments: 15,
    commentsData: [
      {
        _id: 'c11',
        user: {
          _id: 'u16',
          fullName: 'Frank Harrison',
          dp: 'https://random.imagecdn.app/224/224',
        },
        text: 'C’est le genre de contenu pour lequel je te suis.',
        likes: 28,
        reactions: ['fas fa-thumbs-up', 'fas fa-heart'],
        createdAt: new Date(Date.now() - 11 * 3600000),
      },
      {
        _id: 'c12',
        user: {
          _id: 'u17',
          fullName: 'Rick Chapman',
          dp: 'https://random.imagecdn.app/225/225',
        },
        text: 'Le borrow checker, la vraie boss finale. Continue !',
        likes: 11,
        reactions: ['fas fa-heart'],
        createdAt: new Date(Date.now() - 9 * 3600000),
        replies: [
          {
            _id: 'c12r1',
            user: {
              _id: 'u18',
              fullName: 'Jack Harrison',
              dp: 'https://random.imagecdn.app/226/226',
            },
            text: 'Approuvé à 100% !',
            likes: 3,
            reactions: ['fas fa-thumbs-up'],
            createdAt: new Date(Date.now() - 8 * 3600000),
          },
        ],
      },
      {
        _id: 'c13',
        user: {
          _id: 'u19',
          fullName: 'Sam Reynolds',
          dp: 'https://random.imagecdn.app/227/227',
        },
        text: 'Le meilleur jusqu’ici ! J’attends la suite avec impatience.',
        likes: 17,
        reactions: ['fas fa-thumbs-up', 'fas fa-laugh'],
        createdAt: new Date(Date.now() - 5 * 3600000),
      },
    ],
    shares: 80,
    sharesData: [
      {
        _id: 's4',
        user: {
          _id: 'u33',
          fullName: 'Samuel Davis',
          dp: 'https://random.imagecdn.app/233/233',
        },
        sharedAt: new Date(Date.now() - 10 * 86400000),
      },
      {
        _id: 's5',
        user: {
          _id: 'u34',
          fullName: 'Zachary Hansen',
          dp: 'https://random.imagecdn.app/234/234',
        },
        caption: 'Tout le monde devrait voir ça. Je partage avec mon équipe !',
        sharedAt: new Date(Date.now() - 7 * 86400000),
      },
      {
        _id: 's6',
        user: {
          _id: 'u35',
          fullName: 'Isaac Hudson',
          dp: 'https://random.imagecdn.app/235/235',
        },
        sharedAt: new Date(Date.now() - 4 * 86400000),
      },
      {
        _id: 's7',
        user: {
          _id: 'u36',
          fullName: 'Robert Irving',
          dp: 'https://random.imagecdn.app/236/236',
        },
        caption: 'À voir absolument !',
        sharedAt: new Date(Date.now() - 1 * 86400000),
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '4',
    user: {
      _id: '1',
      fullName: 'Léo Martin',
      username: 'leo_martin',
      dp: 'https://random.imagecdn.app/500/200',
    },
    caption: 'Café. Code. Recommencer. ☕',
    image: 'https://random.imagecdn.app/1920/1050',
    likes: 29,
    comments: 1,
    commentsData: [
      {
        _id: 'c14',
        user: {
          _id: 'u20',
          fullName: 'Mark Udell',
          dp: 'https://random.imagecdn.app/228/228',
        },
        text: 'Premier commentaire ! Toujours d’aussi bons posts.',
        likes: 2,
        reactions: ['fas fa-thumbs-up'],
        createdAt: new Date(Date.now() - 1 * 3600000),
      },
    ],
    shares: 2,
    sharesData: [
      {
        _id: 's8',
        user: {
          _id: 'u37',
          fullName: 'Kevin Udell',
          dp: 'https://random.imagecdn.app/237/237',
        },
        sharedAt: new Date(Date.now() - 3 * 86400000),
      },
      {
        _id: 's9',
        user: {
          _id: 'u38',
          fullName: 'Shane Kane',
          dp: 'https://random.imagecdn.app/238/238',
        },
        caption: 'La culture café est réelle ☕',
        sharedAt: new Date(Date.now() - 1 * 86400000),
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '5',
    user: {
      _id: 'u2',
      fullName: 'Sarah Chen',
      username: 'sarah_sec',
      dp: 'https://random.imagecdn.app/212/212',
    },
    caption:
      'J’ai enfin fini d’aménager mon home lab de cybersécurité et je suis littéralement amoureuse du résultat ! Un coin cosy, du bon éclairage et des machines partout — le setup parfait pour mener mes pentests et mes analyses. Votre environnement façonne vraiment votre état d’esprit. 🌿💻',
    image: 'https://random.imagecdn.app/1920/1040',
    likes: 342,
    comments: 18,
    commentsData: [
      {
        _id: 'c15',
        user: {
          _id: 'u3',
          fullName: 'Ryan Cooper',
          dp: 'https://random.imagecdn.app/211/211',
        },
        text: 'Ce setup est incroyable ! Quelle machine pour tes labos ?',
        likes: 14,
        reactions: ['fas fa-thumbs-up', 'fas fa-heart'],
        createdAt: new Date(Date.now() - 3 * 3600000),
        replies: [
          {
            _id: 'c15r1',
            user: {
              _id: 'u2',
              fullName: 'Sarah Chen',
              dp: 'https://random.imagecdn.app/212/212',
            },
            text: 'Un Proxmox avec 8 VMs, un VLAN isolé et Kali en guest. 🌱',
            likes: 8,
            reactions: ['fas fa-thumbs-up'],
            createdAt: new Date(Date.now() - 2 * 3600000),
          },
        ],
      },
      {
        _id: 'c16',
        user: {
          _id: 'u5',
          fullName: 'Tyler Brooks',
          dp: 'https://random.imagecdn.app/213/213',
        },
        text: 'Les vibes de cette photo sont immaculées. Très inspirant !',
        likes: 9,
        reactions: ['fas fa-heart'],
        createdAt: new Date(Date.now() - 2 * 3600000),
      },
    ],
    shares: 12,
    sharesData: [
      {
        _id: 's10',
        user: {
          _id: 'u39',
          fullName: 'Raymond Andrews',
          dp: 'https://random.imagecdn.app/239/239',
        },
        sharedAt: new Date(Date.now() - 6 * 86400000),
      },
      {
        _id: 's11',
        user: {
          _id: 'u40',
          fullName: 'Bradley Hudson',
          dp: 'https://random.imagecdn.app/240/240',
        },
        caption: 'Home lab de rêve ici 🌿',
        sharedAt: new Date(Date.now() - 3 * 86400000),
      },
      {
        _id: 's12',
        user: {
          _id: 'u41',
          fullName: 'Brian Hudson',
          dp: 'https://random.imagecdn.app/241/241',
        },
        sharedAt: new Date(Date.now() - 12 * 3600000),
      },
    ],
    createdAt: new Date(Date.now() - 1 * 3600000),
    updatedAt: new Date(),
  },
  {
    _id: '6',
    user: {
      _id: 'u3',
      fullName: 'Ryan Cooper',
      username: 'ryan_dev',
      dp: 'https://random.imagecdn.app/211/211',
    },
    caption:
      'Premier projet open-source livré aujourd’hui 🚀 Des mois de nuits blanches, d’innombrables refactors et une montagne d’onglets Stack Overflow — mais c’est enfin en ligne ! Si vous êtes développeur, vous connaissez cette sensation. Lien en bio. Vos retours sont les bienvenus !',
    image: 'https://random.imagecdn.app/1920/1030',
    likes: 621,
    comments: 34,
    commentsData: [
      {
        _id: 'c17',
        user: {
          _id: 'u1',
          fullName: 'Léo Martin',
          dp: 'https://random.imagecdn.app/500/200',
        },
        text: 'Félicitations mec ! C’est énorme. Je vais le regarder tout de suite.',
        likes: 27,
        reactions: ['fas fa-thumbs-up', 'fas fa-laugh'],
        createdAt: new Date(Date.now() - 5 * 3600000),
      },
      {
        _id: 'c18',
        user: {
          _id: 'u7',
          fullName: 'Jason Foster',
          dp: 'https://random.imagecdn.app/215/215',
        },
        text: 'Les contributions open-source sont si précieuses. Beau travail !',
        likes: 15,
        reactions: ['fas fa-thumbs-up'],
        createdAt: new Date(Date.now() - 4 * 3600000),
        replies: [
          {
            _id: 'c18r1',
            user: {
              _id: 'u3',
              fullName: 'Ryan Cooper',
              dp: 'https://random.imagecdn.app/211/211',
            },
            text: 'Merci beaucoup ! De nouvelles features arrivent 👨‍💻',
            likes: 6,
            reactions: ['fas fa-thumbs-up'],
            createdAt: new Date(Date.now() - 3 * 3600000),
          },
        ],
      },
    ],
    shares: 45,
    sharesData: [
      {
        _id: 's13',
        user: {
          _id: 'u42',
          fullName: 'Shane Irving',
          dp: 'https://random.imagecdn.app/242/242',
        },
        sharedAt: new Date(Date.now() - 8 * 86400000),
      },
      {
        _id: 's14',
        user: {
          _id: 'u43',
          fullName: 'Liam Hudson',
          dp: 'https://random.imagecdn.app/243/243',
        },
        caption: 'La communauté open-source a besoin de plus de gens comme lui !',
        sharedAt: new Date(Date.now() - 5 * 86400000),
      },
      {
        _id: 's15',
        user: {
          _id: 'u44',
          fullName: 'Timothy Ingram',
          dp: 'https://random.imagecdn.app/244/244',
        },
        sharedAt: new Date(Date.now() - 2 * 86400000),
      },
      {
        _id: 's16',
        user: {
          _id: 'u45',
          fullName: 'Noah Hudson',
          dp: 'https://random.imagecdn.app/245/245',
        },
        caption: 'Je partage pour tous mes amis devs 🚀',
        sharedAt: new Date(Date.now() - 6 * 3600000),
      },
    ],
    createdAt: new Date(Date.now() - 2 * 3600000),
    updatedAt: new Date(),
  },
  {
    _id: '7',
    user: {
      _id: 'u4',
      fullName: 'Tyler Brooks',
      username: 'tyler_ops',
      dp: 'https://random.imagecdn.app/213/213',
    },
    caption:
      'J’ai automatisé le déploiement de toute l’infra ce matin et je n’y crois toujours pas. Il y a six mois je n’avais jamais touché à Terraform. La constance, c’est vraiment tout. Si vous hésitez à vous lancer en DevOps — lancez-vous. Votre futur vous remerciera. 🏃‍♂️🎉',
    image: 'https://random.imagecdn.app/1920/1020',
    likes: 874,
    comments: 61,
    commentsData: [
      {
        _id: 'c19',
        user: {
          _id: 'u6',
          fullName: 'Derek Morgan',
          dp: 'https://random.imagecdn.app/214/214',
        },
        text: 'Tellement inspirant ! Je viens de commencer Terraform cette semaine. 💪',
        likes: 33,
        reactions: ['fas fa-thumbs-up', 'fas fa-heart'],
        createdAt: new Date(Date.now() - 6 * 3600000),
      },
      {
        _id: 'c20',
        user: {
          _id: 'u8',
          fullName: 'Michael Campbell',
          dp: 'https://random.imagecdn.app/216/216',
        },
        text: 'Légende ! Et maintenant, un pipeline CI/CD complet ? 😄',
        likes: 19,
        reactions: ['fas fa-laugh'],
        createdAt: new Date(Date.now() - 4 * 3600000),
        replies: [
          {
            _id: 'c20r1',
            user: {
              _id: 'u4',
              fullName: 'Tyler Brooks',
              dp: 'https://random.imagecdn.app/213/213',
            },
            text: 'Déjà en cours haha ! 😅',
            likes: 11,
            reactions: ['fas fa-laugh', 'fas fa-thumbs-up'],
            createdAt: new Date(Date.now() - 3 * 3600000),
          },
        ],
      },
    ],
    shares: 29,
    sharesData: [
      {
        _id: 's17',
        user: {
          _id: 'u46',
          fullName: 'Matthew Allen',
          dp: 'https://random.imagecdn.app/246/246',
        },
        sharedAt: new Date(Date.now() - 9 * 86400000),
      },
      {
        _id: 's18',
        user: {
          _id: 'u47',
          fullName: 'Sebastian Morgan',
          dp: 'https://random.imagecdn.app/247/247',
        },
        caption: 'Motivation niveau 1000 ! Je commence mon parcours DevOps demain.',
        sharedAt: new Date(Date.now() - 4 * 86400000),
      },
      {
        _id: 's19',
        user: {
          _id: 'u48',
          fullName: 'Spencer Andrews',
          dp: 'https://random.imagecdn.app/248/248',
        },
        sharedAt: new Date(Date.now() - 18 * 3600000),
      },
    ],
    createdAt: new Date(Date.now() - 3 * 3600000),
    updatedAt: new Date(),
  },
  {
    _id: '8',
    user: {
      _id: 'u5',
      fullName: 'Derek Morgan',
      username: 'derek_db',
      dp: 'https://random.imagecdn.app/214/214',
    },
    caption:
      'J’ai essayé de faire de la réplication PostgreSQL avec streaming en premier... et honnêtement, ça s’est mieux passé que prévu ! 🍣 Il y a quelque chose de tellement méditatif dans le tuning des requêtes. Quelqu’un d’autre trouve que la performance DB est un bon moyen de décompresser après une longue semaine ?',
    image: 'https://random.imagecdn.app/1920/1010',
    likes: 198,
    comments: 22,
    commentsData: [
      {
        _id: 'c21',
        user: {
          _id: 'u9',
          fullName: 'Marcus Henderson',
          dp: 'https://random.imagecdn.app/217/217',
        },
        text: 'Il faut nous partager ta config ! Ces résultats sont incroyables 😍',
        likes: 17,
        reactions: ['fas fa-heart'],
        createdAt: new Date(Date.now() - 2 * 3600000),
      },
      {
        _id: 'c22',
        user: {
          _id: 'u11',
          fullName: 'Russell Hansen',
          dp: 'https://random.imagecdn.app/219/219',
        },
        text: 'Le tuning de requêtes, c’est définitivement ma thérapie aussi. Délicieux !',
        likes: 8,
        reactions: ['fas fa-thumbs-up', 'fas fa-heart'],
        createdAt: new Date(Date.now() - 1 * 3600000),
      },
    ],
    shares: 7,
    sharesData: [
      {
        _id: 's20',
        user: {
          _id: 'u49',
          fullName: 'Ian Hudson',
          dp: 'https://random.imagecdn.app/249/249',
        },
        sharedAt: new Date(Date.now() - 2 * 86400000),
      },
      {
        _id: 's21',
        user: {
          _id: 'u50',
          fullName: 'Walter Morgan',
          dp: 'https://random.imagecdn.app/250/250',
        },
        caption: 'Le tuning SQL est aussi ma thérapie ! Super post.',
        sharedAt: new Date(Date.now() - 1 * 86400000),
      },
      {
        _id: 's22',
        user: {
          _id: 'u51',
          fullName: 'Harold Ullman',
          dp: 'https://random.imagecdn.app/251/251',
        },
        sharedAt: new Date(Date.now() - 8 * 3600000),
      },
    ],
    createdAt: new Date(Date.now() - 4 * 3600000),
    updatedAt: new Date(),
  },
];

export const newsData: IStory[] = [
  {
    _id: '1',
    image: 'https://random.imagecdn.app/200/300',
    user: {
      _id: '1',
      fullName: 'The Daily Byte',
      dp: 'https://random.imagecdn.app/100/100',
    },
    createdAt: new Date(),
  },
  {
    _id: '2',
    image: 'https://random.imagecdn.app/200/400',
    user: {
      _id: '2',
      fullName: 'Sécurité Hebdo',
      dp: 'https://random.imagecdn.app/200/200',
    },
    createdAt: new Date(),
  },
  {
    _id: '3',
    image: 'https://random.imagecdn.app/201/300',
    user: {
      _id: '3',
      fullName: 'Hacker Weekly',
      dp: 'https://random.imagecdn.app/201/201',
    },
    createdAt: new Date(),
  },
  {
    _id: '4',
    image: 'https://random.imagecdn.app/202/300',
    user: {
      _id: '4',
      fullName: 'Frontend Daily',
      dp: 'https://random.imagecdn.app/202/202',
    },
    createdAt: new Date(),
  },
  {
    _id: '5',
    image: 'https://random.imagecdn.app/203/300',
    user: {
      _id: '5',
      fullName: 'DevOps Insight',
      dp: 'https://random.imagecdn.app/203/203',
    },
    createdAt: new Date(),
  },
  {
    _id: '6',
    image: 'https://random.imagecdn.app/204/300',
    user: {
      _id: '6',
      fullName: 'Python Pulse',
      dp: 'https://random.imagecdn.app/204/204',
    },
    createdAt: new Date(),
  },
  {
    _id: '7',
    image: 'https://random.imagecdn.app/205/300',
    user: {
      _id: '7',
      fullName: 'Open Source News',
      dp: 'https://random.imagecdn.app/205/205',
    },
    createdAt: new Date(),
  },
  {
    _id: '8',
    image: 'https://random.imagecdn.app/206/300',
    user: {
      _id: '8',
      fullName: 'AI Engineering',
      dp: 'https://random.imagecdn.app/206/206',
    },
    createdAt: new Date(),
  },
];

export const jobListingsData: IJobListing[] = [
  {
    _id: 'jb1',
    salary: 65000,
    title: 'Développeur Fullstack React / Node.js',
    location: 'Remote (France)',
    image: 'https://random.imagecdn.app/300/300',
    category: 'Développement',
    contractType: 'CDI',
    listedAgo: 'il y a 2 jours',
    description:
      'Rejoignez une startup SaaS en pleine croissance.\nStack : React, TypeScript, Node.js, PostgreSQL\nMission : développer des features produit de bout en bout\nAvantages : télétravail complet, budget formation',
    images: [
      'https://random.imagecdn.app/300/300',
      'https://random.imagecdn.app/300/302',
      'https://random.imagecdn.app/302/300',
      'https://random.imagecdn.app/298/300',
      'https://random.imagecdn.app/300/298',
    ],
    company: {
      _id: 'co1',
      name: 'DevForge',
      dp: 'https://random.imagecdn.app/211/211',
      responsive: true,
      joinedYear: 2019,
    },
  },
  {
    _id: 'jb2',
    salary: 82000,
    title: 'Ingénieur Cybersécurité Offensive (Pentest)',
    location: 'Paris, France',
    image: 'https://random.imagecdn.app/301/301',
    category: 'Cybersécurité',
    contractType: 'CDI',
    listedAgo: 'il y a 3 heures',
    description:
      'Poste au sein d’une équipe Red Team.\nOSCP ou équivalent apprécié\nRéalisation de tests d’intrusion web, réseau et applicatif\nRédaction de rapports pour des clients grands comptes',
    images: [
      'https://random.imagecdn.app/301/301',
      'https://random.imagecdn.app/301/303',
      'https://random.imagecdn.app/303/301',
      'https://random.imagecdn.app/299/301',
      'https://random.imagecdn.app/301/299',
    ],
    company: {
      _id: 'co2',
      name: 'SecLab',
      dp: 'https://random.imagecdn.app/213/213',
      responsive: true,
      joinedYear: 2020,
    },
  },
  {
    _id: 'jb3',
    salary: 58000,
    title: 'DevOps Engineer Kubernetes',
    location: 'Lyon, France',
    image: 'https://random.imagecdn.app/302/302',
    category: 'DevOps',
    contractType: 'CDI',
    listedAgo: 'il y a 5 jours',
    description:
      'Gestion de clusters Kubernetes de production\nTerraform, Ansible, GitLab CI\nBonus : expérience AWS ou Azure\nTravail hybride 2 jours/semaine',
    images: [
      'https://random.imagecdn.app/302/302',
      'https://random.imagecdn.app/302/304',
      'https://random.imagecdn.app/304/302',
      'https://random.imagecdn.app/300/302',
      'https://random.imagecdn.app/302/300',
      'https://random.imagecdn.app/306/302',
    ],
    company: {
      _id: 'co3',
      name: 'CloudOps',
      dp: 'https://random.imagecdn.app/215/215',
      responsive: false,
      joinedYear: 2018,
    },
  },
  {
    _id: 'jb4',
    salary: 0,
    isFree: true,
    title: 'Contributeur open-source — kit UI accessible',
    location: 'Remote (Monde entier)',
    image: 'https://random.imagecdn.app/303/303',
    category: 'Open Source',
    contractType: 'Open Source',
    listedAgo: 'il y a une semaine',
    description:
      'Projet communautaire de composants accessibles.\nReact + TypeScript + Tailwind\nContributions sur les issues good first issue\nMentorat par les mainteneurs',
    images: [
      'https://random.imagecdn.app/303/303',
      'https://random.imagecdn.app/303/305',
      'https://random.imagecdn.app/305/303',
      'https://random.imagecdn.app/301/303',
      'https://random.imagecdn.app/307/303',
    ],
    company: {
      _id: 'co4',
      name: 'OpenKit',
      dp: 'https://random.imagecdn.app/212/212',
      responsive: true,
      joinedYear: 2017,
    },
  },
  {
    _id: 'jb5',
    salary: 450,
    title: 'Freelance — refonte d’un site vitrine (React)',
    location: 'Remote',
    image: 'https://random.imagecdn.app/304/304',
    category: 'Freelance',
    contractType: 'Freelance',
    listedAgo: 'il y a un jour',
    description:
      'Refonte complète d’un site vitrine pour une PME.\nBudget : 4 500 €\nDesign existant fourni\nDélai : 3 semaines\nStack libre mais React recommandé',
    images: [
      'https://random.imagecdn.app/304/304',
      'https://random.imagecdn.app/304/306',
      'https://random.imagecdn.app/306/304',
      'https://random.imagecdn.app/302/304',
    ],
    company: {
      _id: 'co1',
      name: 'DevForge',
      dp: 'https://random.imagecdn.app/211/211',
      responsive: true,
      joinedYear: 2019,
    },
  },
  {
    _id: 'jb6',
    salary: 52000,
    title: 'Data Engineer Python / Spark',
    location: 'Bordeaux, France',
    image: 'https://random.imagecdn.app/305/305',
    category: 'Data & IA',
    contractType: 'CDI',
    listedAgo: 'il y a 4 jours',
    description:
      'Construction de pipelines de données.\nPython, Apache Spark, Airflow\nExpérience cloud appréciée\nAmbiance d’équipe très soudée',
    images: [
      'https://random.imagecdn.app/305/305',
      'https://random.imagecdn.app/305/307',
      'https://random.imagecdn.app/307/305',
      'https://random.imagecdn.app/303/305',
    ],
    company: {
      _id: 'co5',
      name: 'DataWaves',
      dp: 'https://random.imagecdn.app/214/214',
      responsive: true,
      joinedYear: 2021,
    },
  },
  {
    _id: 'jb7',
    salary: 60000,
    title: 'Développeur Mobile Flutter',
    location: 'Remote (Europe)',
    image: 'https://random.imagecdn.app/306/306',
    category: 'Mobile',
    contractType: 'CDI',
    listedAgo: 'il y a 6 heures',
    description:
      'Développement d’une app Flutter grand public.\n3+ ans d’expérience mobile\nCI/CD avec Codemagic\nStore : Play + App Store',
    images: [
      'https://random.imagecdn.app/306/306',
      'https://random.imagecdn.app/306/308',
      'https://random.imagecdn.app/308/306',
      'https://random.imagecdn.app/304/306',
      'https://random.imagecdn.app/306/304',
    ],
    company: {
      _id: 'co2',
      name: 'SecLab',
      dp: 'https://random.imagecdn.app/213/213',
      responsive: true,
      joinedYear: 2020,
    },
  },
  {
    _id: 'jb8',
    salary: 75000,
    title: 'Lead Backend Engineer (Go)',
    location: 'Toulouse, France',
    image: 'https://random.imagecdn.app/307/307',
    category: 'Développement',
    contractType: 'CDI',
    listedAgo: 'il y a 2 semaines',
    description:
      'Encadrement d’une équipe de 5 développeurs.\nGo, gRPC, microservices\nConception d’API haut débit\nStack Kafka et Redis',
    images: [
      'https://random.imagecdn.app/307/307',
      'https://random.imagecdn.app/307/309',
      'https://random.imagecdn.app/309/307',
      'https://random.imagecdn.app/305/307',
      'https://random.imagecdn.app/311/307',
      'https://random.imagecdn.app/307/305',
    ],
    company: {
      _id: 'co6',
      name: 'GoCore',
      dp: 'https://random.imagecdn.app/216/216',
      responsive: false,
      joinedYear: 2016,
    },
  },
  {
    _id: 'jb9',
    salary: 38000,
    title: 'Développeur Frontend Junior (React)',
    location: 'Nantes, France',
    image: 'https://random.imagecdn.app/308/308',
    category: 'Développement',
    contractType: 'CDD',
    listedAgo: 'il y a 3 jours',
    description:
      'CDD de 12 mois pour un premier poste.\nReact, TypeScript, accessibilité\nMentorat et montée en compétences\nPortfolio apprécié',
    images: [
      'https://random.imagecdn.app/308/308',
      'https://random.imagecdn.app/308/310',
      'https://random.imagecdn.app/310/308',
      'https://random.imagecdn.app/306/308',
    ],
    company: {
      _id: 'co5',
      name: 'DataWaves',
      dp: 'https://random.imagecdn.app/214/214',
      responsive: true,
      joinedYear: 2021,
    },
  },
  {
    _id: 'jb10',
    salary: 55000,
    title: 'Security Engineer (Blue Team)',
    location: 'Rennes, France',
    image: 'https://random.imagecdn.app/309/309',
    category: 'Cybersécurité',
    contractType: 'CDI',
    listedAgo: 'il y a 5 heures',
    description:
      'Surveillance et réponse aux incidents.\nSIEM, EDR, threat hunting\nSensibilisation des équipes\nSalaire selon profil',
    images: [
      'https://random.imagecdn.app/309/309',
      'https://random.imagecdn.app/309/311',
      'https://random.imagecdn.app/311/309',
      'https://random.imagecdn.app/307/309',
      'https://random.imagecdn.app/313/309',
    ],
    company: {
      _id: 'co3',
      name: 'CloudOps',
      dp: 'https://random.imagecdn.app/215/215',
      responsive: false,
      joinedYear: 2018,
    },
  },
  {
    _id: 'jb11',
    salary: 70000,
    title: 'Ingénieur IA / Machine Learning',
    location: 'Remote (France)',
    image: 'https://random.imagecdn.app/310/310',
    category: 'Data & IA',
    contractType: 'CDI',
    listedAgo: 'il y a 10 jours',
    description:
      'Développement de modèles de NLP.\nPyTorch, Hugging Face, Python\nMise en production via MLOps\nDoctorat apprécié mais pas obligatoire',
    images: [
      'https://random.imagecdn.app/310/310',
      'https://random.imagecdn.app/310/312',
      'https://random.imagecdn.app/312/310',
      'https://random.imagecdn.app/308/310',
      'https://random.imagecdn.app/314/310',
      'https://random.imagecdn.app/310/308',
    ],
    company: {
      _id: 'co4',
      name: 'OpenKit',
      dp: 'https://random.imagecdn.app/212/212',
      responsive: true,
      joinedYear: 2017,
    },
  },
  {
    _id: 'jb12',
    salary: 48000,
    title: 'Développeur Fullstack PHP / Symfony',
    location: 'Lille, France',
    image: 'https://random.imagecdn.app/311/311',
    category: 'Développement',
    contractType: 'CDI',
    listedAgo: 'il y a 12 heures',
    description:
      'Maintien et évolution d’une plateforme e-commerce.\nPHP 8, Symfony 6, MySQL\nAPI REST et paiement en ligne\nÉquipe de 6 personnes',
    images: [
      'https://random.imagecdn.app/311/311',
      'https://random.imagecdn.app/311/313',
      'https://random.imagecdn.app/313/311',
      'https://random.imagecdn.app/309/311',
    ],
    company: {
      _id: 'co1',
      name: 'DevForge',
      dp: 'https://random.imagecdn.app/211/211',
      responsive: true,
      joinedYear: 2019,
    },
  },
  {
    _id: 'jb13',
    salary: 0,
    isFree: true,
    title: 'Mission bénévole — site web associatif',
    location: 'Remote',
    image: 'https://random.imagecdn.app/312/312',
    category: 'Open Source',
    contractType: 'Open Source',
    listedAgo: 'à l’instant',
    description:
      'Besoin d’aide pour un site d’association caritative.\nStack libre : Astro ou Next.js\nPages statiques + formulaire de don\nReconnaissance et goodies à la clé',
    images: [
      'https://random.imagecdn.app/312/312',
      'https://random.imagecdn.app/312/314',
      'https://random.imagecdn.app/314/312',
    ],
    company: {
      _id: 'co5',
      name: 'DataWaves',
      dp: 'https://random.imagecdn.app/214/214',
      responsive: true,
      joinedYear: 2021,
    },
  },
  {
    _id: 'jb14',
    salary: 68000,
    title: 'Développeur Fullstack Senior (Vue.js)',
    location: 'Remote (Europe)',
    image: 'https://random.imagecdn.app/313/313',
    category: 'Développement',
    contractType: 'CDI',
    listedAgo: 'il y a un jour',
    description:
      'Poste senior au sein d’une scale-up internationale.\nVue 3, TypeScript, NestJS\nExigence : excellent niveau en architecture\nEnglish working environment',
    images: [
      'https://random.imagecdn.app/313/313',
      'https://random.imagecdn.app/313/315',
      'https://random.imagecdn.app/315/313',
      'https://random.imagecdn.app/311/313',
      'https://random.imagecdn.app/317/313',
      'https://random.imagecdn.app/313/311',
    ],
    company: {
      _id: 'co7',
      name: 'ScaleUp',
      dp: 'https://random.imagecdn.app/270/270',
      responsive: true,
      joinedYear: 2022,
    },
  },
  {
    _id: 'jb15',
    salary: 50000,
    title: 'Développeur WordPress / WooCommerce',
    location: 'Strasbourg, France',
    image: 'https://random.imagecdn.app/314/314',
    category: 'Développement',
    contractType: 'CDI',
    listedAgo: 'il y a 2 jours',
    description:
      'Développement de thèmes et plugins sur mesure.\nPHP, Gutenberg, WooCommerce\nPerformance et SEO\nHybride 2 jours/semaine',
    images: [
      'https://random.imagecdn.app/314/314',
      'https://random.imagecdn.app/314/316',
      'https://random.imagecdn.app/316/314',
      'https://random.imagecdn.app/312/314',
      'https://random.imagecdn.app/318/314',
    ],
    company: {
      _id: 'co6',
      name: 'GoCore',
      dp: 'https://random.imagecdn.app/216/216',
      responsive: false,
      joinedYear: 2016,
    },
  },
  {
    _id: 'jb16',
    salary: 62000,
    title: 'Tech Lead Frontend (React Native)',
    location: 'Marseille, France',
    image: 'https://random.imagecdn.app/315/315',
    category: 'Mobile',
    contractType: 'CDI',
    listedAgo: 'il y a 4 jours',
    description:
      'Lead technique d’une app mobile bancaire.\nReact Native, TypeScript\nCoordination avec iOS/Android\nGouvernance technique et review de code',
    images: [
      'https://random.imagecdn.app/315/315',
      'https://random.imagecdn.app/315/317',
      'https://random.imagecdn.app/317/315',
      'https://random.imagecdn.app/313/315',
    ],
    company: {
      _id: 'co2',
      name: 'SecLab',
      dp: 'https://random.imagecdn.app/213/213',
      responsive: true,
      joinedYear: 2020,
    },
  },
  {
    _id: 'jb17',
    salary: 44000,
    title: 'Intégrateur / Développeur Frontend',
    location: 'Grenoble, France',
    image: 'https://random.imagecdn.app/316/316',
    category: 'Développement',
    contractType: 'CDD',
    listedAgo: 'il y a 3 jours',
    description:
      'Intégration de maquettes Figma.\nHTML, CSS, JavaScript vanilla\nPuis montée en compétences React\nEnvironnement bienveillant',
    images: [
      'https://random.imagecdn.app/316/316',
      'https://random.imagecdn.app/316/318',
      'https://random.imagecdn.app/318/316',
      'https://random.imagecdn.app/314/316',
      'https://random.imagecdn.app/316/314',
    ],
    company: {
      _id: 'co7',
      name: 'ScaleUp',
      dp: 'https://random.imagecdn.app/270/270',
      responsive: true,
      joinedYear: 2022,
    },
  },
  {
    _id: 'jb18',
    salary: 56000,
    title: 'DevOps / SRE — plateformes haute dispo',
    location: 'Remote (France)',
    image: 'https://random.imagecdn.app/317/317',
    category: 'DevOps',
    contractType: 'CDI',
    listedAgo: 'il y a 6 jours',
    description:
      'Fiabilité des plateformes critiques.\nGolang, Kubernetes, Prometheus\nOn-call rémunéré\nFort focus observabilité',
    images: [
      'https://random.imagecdn.app/317/317',
      'https://random.imagecdn.app/317/319',
      'https://random.imagecdn.app/319/317',
      'https://random.imagecdn.app/315/317',
      'https://random.imagecdn.app/317/315',
    ],
    company: {
      _id: 'co3',
      name: 'CloudOps',
      dp: 'https://random.imagecdn.app/215/215',
      responsive: false,
      joinedYear: 2018,
    },
  },
];

const GTV = 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample';

export const shortsData: IShort[] = [
  {
    _id: 'sh1',
    user: {
      _id: 'u60',
      fullName: 'Dev Tips',
      username: 'dev_tips',
      dp: 'https://random.imagecdn.app/260/260',
      isVerified: true,
      isFollowing: false,
    },
    videoUrl: `${GTV}/ForBiggerBlazes.mp4`,
    poster: 'https://random.imagecdn.app/400/711',
    caption:
      '3 raccourcis VS Code qui changent votre quotidien 😍 À connaître absolument.',
    audio: 'Dev Tips · Audio original',
    likes: 116,
    comments: 129,
    shares: 20,
    createdAt: new Date(Date.now() - 9 * 3600000),
  },
  {
    _id: 'sh2',
    user: {
      _id: 'u61',
      fullName: 'Ryan Dev',
      username: 'ryan_dev',
      dp: 'https://random.imagecdn.app/261/261',
      isVerified: false,
      isFollowing: true,
    },
    videoUrl: `${GTV}/ForBiggerEscapes.mp4`,
    poster: 'https://random.imagecdn.app/401/711',
    caption:
      'Une app fullstack en 60 minutes avec React + Node. Voici comment 🚀 #coding #webdev',
    audio: 'Lofi Study Beats · Chill Mix',
    likes: 2400,
    comments: 318,
    shares: 145,
    createdAt: new Date(Date.now() - 5 * 3600000),
  },
  {
    _id: 'sh3',
    user: {
      _id: 'u62',
      fullName: 'Cybersec Académie',
      username: 'cybersec_academy',
      dp: 'https://random.imagecdn.app/262/262',
      isVerified: true,
      isFollowing: false,
    },
    videoUrl: `${GTV}/ForBiggerFun.mp4`,
    poster: 'https://random.imagecdn.app/402/711',
    caption:
      'Comprendre les attaques par injection SQL en 60 secondes 🎯 Un classique du pentest.',
    audio: 'Cybersec Académie · Audio original',
    likes: 8700,
    comments: 542,
    shares: 892,
    createdAt: new Date(Date.now() - 14 * 3600000),
  },
  {
    _id: 'sh4',
    user: {
      _id: 'u63',
      fullName: 'Code With Emily',
      username: 'emily_codes',
      dp: 'https://random.imagecdn.app/263/263',
      isVerified: false,
      isFollowing: false,
    },
    videoUrl: `${GTV}/ForBiggerJoyrides.mp4`,
    poster: 'https://random.imagecdn.app/403/711',
    caption:
      '5 astuces CSS qui transforment n’importe quel site en 5 minutes 🍣 Code dans les commentaires !',
    audio: 'Coding Vibes · Chill House',
    likes: 3200,
    comments: 411,
    shares: 267,
    createdAt: new Date(Date.now() - 22 * 3600000),
  },
  {
    _id: 'sh5',
    user: {
      _id: 'u64',
      fullName: 'Tyler DevOps',
      username: 'tyler_devops',
      dp: 'https://random.imagecdn.app/264/264',
      isVerified: false,
      isFollowing: true,
    },
    videoUrl: `${GTV}/ForBiggerMeltdowns.mp4`,
    poster: 'https://random.imagecdn.app/404/711',
    caption:
      'Déployer avec Docker en 45 secondes. Il y a six mois je ne savais pas ce qu’était un container 💪',
    audio: 'Dev Motivation · DJ Mix',
    likes: 12400,
    comments: 730,
    shares: 1100,
    createdAt: new Date(Date.now() - 2 * 86400000),
  },
  {
    _id: 'sh6',
    user: {
      _id: 'u65',
      fullName: 'Michael Speaks',
      username: 'michael_speaks',
      dp: 'https://random.imagecdn.app/265/265',
      isVerified: true,
      isFollowing: false,
    },
    videoUrl: `${GTV}/BigBuckBunny.mp4`,
    poster: 'https://random.imagecdn.app/405/711',
    caption:
      'Arrête d’attendre le moment parfait. Lance-toi, parfait plus tard. 🔥 #dev #mindset',
    audio: 'Michael Speaks · Audio original',
    likes: 45000,
    comments: 2100,
    shares: 6800,
    createdAt: new Date(Date.now() - 3 * 86400000),
  },
  {
    _id: 'sh7',
    user: {
      _id: 'u66',
      fullName: 'Tech With Frank',
      username: 'tech_frank',
      dp: 'https://random.imagecdn.app/266/266',
      isVerified: false,
      isFollowing: false,
    },
    videoUrl: `${GTV}/TearsOfSteel.mp4`,
    poster: 'https://random.imagecdn.app/406/711',
    caption:
      'Pourquoi vous devriez contribuer à l’open-source cette année — mon retour d’expérience 📦',
    audio: 'Tech With Frank · Audio original',
    likes: 5600,
    comments: 890,
    shares: 340,
    createdAt: new Date(Date.now() - 4 * 86400000),
  },
  {
    _id: 'sh8',
    user: {
      _id: 'u67',
      fullName: 'AI Daily',
      username: 'ai_daily',
      dp: 'https://random.imagecdn.app/267/267',
      isVerified: false,
      isFollowing: true,
    },
    videoUrl: `${GTV}/WeAreGoingOnBullrun.mp4`,
    poster: 'https://random.imagecdn.app/407/711',
    caption:
      'Comment j’utilise les LLMs pour coder 2x plus vite, sans perdre en qualité ☀️',
    audio: 'Morning Calm · Meditation Mix',
    likes: 19200,
    comments: 1430,
    shares: 3200,
    createdAt: new Date(Date.now() - 5 * 86400000),
  },
];

export const featuredChallengesData: IChallenge[] = [
  {
    _id: 'c1',
    title: 'Code quotidien — 30 jours de JS',
    image: 'https://random.imagecdn.app/320/321',
    category: 'Algorithmes',
    participants: [
      { _id: 'cp1', dp: 'https://random.imagecdn.app/50/51' },
      { _id: 'cp2', dp: 'https://random.imagecdn.app/51/50' },
      { _id: 'cp3', dp: 'https://random.imagecdn.app/52/50' },
    ],
  },
  {
    _id: 'c2',
    title: 'CTF : Piratez la machine',
    image: 'https://random.imagecdn.app/321/320',
    category: 'Cybersécurité',
    participants: [
      { _id: 'cp4', dp: 'https://random.imagecdn.app/53/50' },
      { _id: 'cp5', dp: 'https://random.imagecdn.app/54/50' },
    ],
  },
  {
    _id: 'c3',
    title: 'CSS Battle #42',
    image: 'https://random.imagecdn.app/322/320',
    category: 'Frontend',
    participants: [
      { _id: 'cp6', dp: 'https://random.imagecdn.app/55/50' },
      { _id: 'cp7', dp: 'https://random.imagecdn.app/56/50' },
      { _id: 'cp8', dp: 'https://random.imagecdn.app/57/50' },
    ],
  },
  {
    _id: 'c4',
    title: 'API Sprint — une API en 1h',
    image: 'https://random.imagecdn.app/323/320',
    category: 'Backend',
  },
  {
    _id: 'c5',
    title: 'Hackathon Open Source 2026',
    image: 'https://random.imagecdn.app/324/320',
    category: 'Hackathon',
  },
  {
    _id: 'c6',
    title: 'Défi Docker : 12 jours',
    image: 'https://random.imagecdn.app/325/320',
    category: 'DevOps',
  },
  {
    _id: 'c7',
    title: 'Reverse Engineering Challenge',
    image: 'https://random.imagecdn.app/326/320',
    category: 'Cybersécurité',
    participants: [
      { _id: 'cp9', dp: 'https://random.imagecdn.app/58/50' },
      { _id: 'cp10', dp: 'https://random.imagecdn.app/59/50' },
    ],
  },
  {
    _id: 'c8',
    title: 'Landing page de la semaine',
    image: 'https://random.imagecdn.app/327/320',
    category: 'Frontend',
  },
  {
    _id: 'c9',
    title: 'Algo Sprint hebdomadaire',
    image: 'https://random.imagecdn.app/328/320',
    category: 'Algorithmes',
    participants: [
      { _id: 'cp11', dp: 'https://random.imagecdn.app/60/50' },
      { _id: 'cp12', dp: 'https://random.imagecdn.app/61/50' },
      { _id: 'cp13', dp: 'https://random.imagecdn.app/62/50' },
    ],
  },
  {
    _id: 'c10',
    title: 'Défi Flask : mini SaaS',
    image: 'https://random.imagecdn.app/329/320',
    category: 'Fullstack',
  },
  {
    _id: 'c11',
    title: 'Kaggle-like : prédiction météo',
    image: 'https://random.imagecdn.app/330/320',
    category: 'Data & IA',
    participants: [
      { _id: 'cp14', dp: 'https://random.imagecdn.app/63/50' },
      { _id: 'cp15', dp: 'https://random.imagecdn.app/64/50' },
    ],
  },
  {
    _id: 'c12',
    title: 'Portfolio React express',
    image: 'https://random.imagecdn.app/331/320',
    category: 'Frontend',
  },
  {
    _id: 'c13',
    title: 'Cracking the Interview',
    image: 'https://random.imagecdn.app/332/320',
    category: 'Algorithmes',
  },
  {
    _id: 'c14',
    title: 'Write your own shell (C)',
    image: 'https://random.imagecdn.app/333/320',
    category: 'Backend',
  },
  {
    _id: 'c15',
    title: 'Sécurise ton API — audit',
    image: 'https://random.imagecdn.app/334/320',
    category: 'Cybersécurité',
  },
  {
    _id: 'c16',
    title: 'Mobile UI Clone Battle',
    image: 'https://random.imagecdn.app/335/320',
    category: 'Mobile',
  },
];

export const challengeEventsData: IChallengeEvent[] = [
  {
    _id: 'ce1',
    challengeTitle: 'CTF National',
    challengeIcon: 'https://random.imagecdn.app/48/48',
    eventImage: 'https://random.imagecdn.app/400/560',
    title: 'Capture The Flag — édition été',
    description:
      'Fêtez l’été avec 48h de challenges de sécurité : web, crypto, forensics et pwn !',
    endsInDays: 11,
  },
  {
    _id: 'ce2',
    challengeTitle: 'Hackathon IA',
    challengeIcon: 'https://random.imagecdn.app/49/48',
    eventImage: 'https://random.imagecdn.app/401/560',
    title: 'IA pour le bien commun',
    description:
      'Construisez en 72h une solution IA utile pour l’environnement et la société.',
    endsInDays: 12,
  },
  {
    _id: 'ce3',
    challengeTitle: 'Frontend Showdown',
    challengeIcon: 'https://random.imagecdn.app/50/48',
    eventImage: 'https://random.imagecdn.app/402/560',
    title: 'La plus belle animation CSS',
    description:
      'Les 10 meilleures animations CSS soumises par la communauté seront récompensées.',
    endsInDays: 12,
  },
  {
    _id: 'ce4',
    challengeTitle: 'Algo Masters',
    challengeIcon: 'https://random.imagecdn.app/51/48',
    eventImage: 'https://random.imagecdn.app/403/560',
    title: 'Tournoi d’algorithmique',
    description:
      'Résolvez des problèmes complexes et grimpez au classement mondial.',
    endsInDays: 12,
  },
  {
    _id: 'ce5',
    challengeTitle: 'DevOps Battle',
    challengeIcon: 'https://random.imagecdn.app/52/48',
    eventImage: 'https://random.imagecdn.app/404/560',
    title: 'Le déploiement le plus rapide',
    description:
      'Qui déploiera l’application la plus robuste en moins de temps ? Défi Kubernetes.',
    endsInDays: 8,
  },
  {
    _id: 'ce6',
    challengeTitle: 'Security Puzzle',
    challengeIcon: 'https://random.imagecdn.app/53/48',
    eventImage: 'https://random.imagecdn.app/405/560',
    title: 'Lancement du week-end crypto',
    description:
      'Déchiffrez des messages chiffrés et remportez des récompenses en NFT dev !',
    endsInDays: 7,
  },
  {
    _id: 'ce7',
    challengeTitle: 'Open Source Fest',
    challengeIcon: 'https://random.imagecdn.app/54/48',
    eventImage: 'https://random.imagecdn.app/406/560',
    title: 'Grande compétition de contributions',
    description:
      'Competez dans le tournoi ultime de l’open source. Gagnez des trophées de contributeur.',
    endsInDays: 15,
  },
];

export const trendingChallengesData: IChallenge[] = [
  {
    _id: 'tc1',
    title: 'CTF Machine : Windows',
    image: 'https://random.imagecdn.app/340/341',
    category: 'Cybersécurité',
  },
  {
    _id: 'tc2',
    title: 'Algorithmes — TSP',
    image: 'https://random.imagecdn.app/341/340',
    category: 'Algorithmes',
  },
  {
    _id: 'tc3',
    title: 'Wordle en 100 lignes',
    image: 'https://random.imagecdn.app/342/340',
    category: 'Frontend',
  },
  {
    _id: 'tc4',
    title: 'Terraform Challenge',
    image: 'https://random.imagecdn.app/343/340',
    category: 'DevOps',
  },
  {
    _id: 'tc5',
    title: 'Regex Battle',
    image: 'https://random.imagecdn.app/344/340',
    category: 'Backend',
  },
  {
    _id: 'tc6',
    title: 'Neural Net from scratch',
    image: 'https://random.imagecdn.app/345/340',
    category: 'Data & IA',
  },
  {
    _id: 'tc7',
    title: 'Solitaire de code',
    image: 'https://random.imagecdn.app/346/340',
    category: 'Algorithmes',
  },
  {
    _id: 'tc8',
    title: 'UI Clone Battle',
    image: 'https://random.imagecdn.app/347/340',
    category: 'Frontend',
  },
];

export const communitiesData: IGroup[] = [
  {
    _id: 'grp1',
    name: 'React France 🇫🇷',
    image: 'https://random.imagecdn.app/360/360',
    lastActive: 'Actif il y a 5 minutes',
    isPinned: true,
    members: 12400,
  },
  {
    _id: 'grp2',
    name: 'CyberSec FR — la sécurité sans bullshit',
    image: 'https://random.imagecdn.app/361/361',
    lastActive: 'Actif il y a 44 minutes',
    members: 8730,
  },
  {
    _id: 'grp3',
    name: 'Python Devs & Data',
    image: 'https://random.imagecdn.app/362/362',
    lastActive: 'Actif il y a 58 minutes',
    members: 32100,
  },
  {
    _id: 'grp4',
    name: 'DevOps & Cloud Community',
    image: 'https://random.imagecdn.app/363/363',
    lastActive: 'Actif il y a 6 heures',
    members: 15400,
  },
  {
    _id: 'grp5',
    name: 'Node.js Enthusiasts',
    image: 'https://random.imagecdn.app/364/364',
    lastActive: 'Actif il y a 8 heures',
    members: 18900,
  },
  {
    _id: 'grp6',
    name: 'Mobile Devs (Flutter & RN)',
    image: 'https://random.imagecdn.app/365/365',
    lastActive: 'Actif il y a un jour',
    members: 7800,
  },
  {
    _id: 'grp7',
    name: 'Web Security & Bug Bounty',
    image: 'https://random.imagecdn.app/366/366',
    lastActive: 'Actif il y a 19 minutes',
    members: 5200,
  },
  {
    _id: 'grp8',
    name: 'Open Source First',
    image: 'https://random.imagecdn.app/367/367',
    lastActive: 'Actif il y a 2 heures',
    members: 23600,
  },
  {
    _id: 'grp9',
    name: 'Laravel & PHP Communauté',
    image: 'https://random.imagecdn.app/368/368',
    lastActive: 'Actif il y a 46 minutes',
    members: 9100,
  },
  {
    _id: 'grp10',
    name: 'AI & LLM Engineering',
    image: 'https://random.imagecdn.app/369/369',
    lastActive: 'Actif il y a une semaine',
    members: 19800,
  },
];

export const communityPostsData: IGroupPost[] = [
  {
    _id: 'gcp1',
    group: {
      _id: 'grp-react',
      name: 'React France 🇫🇷',
      image: 'https://random.imagecdn.app/370/370',
      isPublic: true,
    },
    user: {
      _id: 'gu1',
      fullName: 'Andy Montesino',
      dp: 'https://random.imagecdn.app/371/371',
      badge: 'Contributeur star',
    },
    content:
      'Qu’est-ce que vous automatisez avec React que vous auriez toujours rêvé d’automatiser ? Je cherche des idées pour un nouvel outil de génération de composants.',
    createdAt: new Date(Date.now() - 4 * 86400000),
    likes: 92,
    likeReactions: ['fas fa-thumbs-up'],
    commentsCount: 166,
    sharesCount: 5,
    comments: [
      {
        _id: 'gc1',
        user: {
          _id: 'gu2',
          fullName: 'OD Mansfield',
          dp: 'https://random.imagecdn.app/372/372',
        },
        text: 'Chaque vendredi, je génère automatiquement la doc des composants à partir des stories. Un vrai gain de temps !',
        likes: 80,
        reactions: ['fas fa-thumbs-up', 'fas fa-heart', 'fas fa-surprise'],
        createdAt: new Date(Date.now() - 3 * 86400000),
        replyCount: 29,
      },
      {
        _id: 'gc2',
        user: {
          _id: 'gu3',
          fullName: 'DeterminedHedgehog000',
          dp: 'https://random.imagecdn.app/373/373',
        },
        text: 'J’ai fait un générateur de tests unitaires à partir de mes propTypes. Maintenant je peux tout tester, n’importe quand.',
        likes: 41,
        reactions: ['fas fa-thumbs-up', 'fas fa-laugh'],
        createdAt: new Date(Date.now() - 3 * 86400000),
        replyCount: 0,
      },
    ],
  },
  {
    _id: 'gcp2',
    group: {
      _id: 'grp-react',
      name: 'React France 🇫🇷',
      image: 'https://random.imagecdn.app/370/370',
      isPublic: true,
    },
    user: {
      _id: 'gu4',
      fullName: 'Alex Bennett',
      dp: 'https://random.imagecdn.app/374/374',
      badge: 'Top contributeur',
    },
    content:
      'Je cherche un co-fondateur technique spécialisé en React Native et en croissance produit.\n\nBasé en Europe.\n\nMinimum 5 ans d’expérience.',
    createdAt: new Date(Date.now() - 23 * 3600000),
    likes: 22,
    likeReactions: ['fas fa-thumbs-up', 'fas fa-laugh'],
    commentsCount: 31,
    sharesCount: 0,
    comments: [
      {
        _id: 'gc3',
        user: {
          _id: 'gu5',
          fullName: 'Jacob Higgins',
          dp: 'https://random.imagecdn.app/375/375',
          isVerified: true,
          isFollowing: true,
        },
        text: 'J’espère que tu trouveras. Je reçois cette offre 5+ fois par jour, peu de gens sont de vrais opérateurs.',
        likes: 3,
        reactions: ['fas fa-thumbs-up'],
        createdAt: new Date(Date.now() - 22 * 3600000),
        replyCount: 1,
      },
      {
        _id: 'gc4',
        user: {
          _id: 'gu6',
          fullName: 'Brad Brown',
          dp: 'https://random.imagecdn.app/376/376',
          isVerified: true,
        },
        text: 'Hahahaha pourquoi ne pas tenter sur d’autres fuseaux horaires ? 😄',
        likes: 0,
        reactions: [],
        createdAt: new Date(Date.now() - 21 * 3600000),
        replyCount: 0,
      },
    ],
  },
  {
    _id: 'gcp3',
    group: {
      _id: 'grp-nodejs',
      name: 'Node.js Enthusiasts',
      image: 'https://random.imagecdn.app/364/364',
      isPublic: false,
    },
    user: {
      _id: 'gu7',
      fullName: 'Ryan Dev',
      dp: 'https://random.imagecdn.app/377/377',
      badge: 'Admin',
    },
    content:
      'Je viens de publier un nouveau package open-source Node.js pour gérer l’authentification JWT avec rotation des refresh tokens. Vos retours sont les bienvenus ! 🚀\n\n⭐ Lien GitHub dans les commentaires.',
    createdAt: new Date(Date.now() - 5 * 3600000),
    likes: 148,
    likeReactions: ['fas fa-thumbs-up', 'fas fa-heart'],
    commentsCount: 42,
    sharesCount: 17,
    comments: [
      {
        _id: 'gc5',
        user: {
          _id: 'gu8',
          fullName: 'Tyler Brooks',
          dp: 'https://random.imagecdn.app/378/378',
        },
        text: 'C’est exactement ce qu’il me fallait ! Je l’intègre dans mon projet actuel.',
        likes: 12,
        reactions: ['fas fa-thumbs-up'],
        createdAt: new Date(Date.now() - 4 * 3600000),
        replyCount: 2,
      },
      {
        _id: 'gc6',
        user: {
          _id: 'gu9',
          fullName: 'Emily Carter',
          dp: 'https://random.imagecdn.app/379/379',
        },
        text: 'Est-ce que ça gère les sessions multi-appareils ? Ce serait top pour mobile + web.',
        likes: 7,
        reactions: ['fas fa-thumbs-up'],
        createdAt: new Date(Date.now() - 3 * 3600000),
        replyCount: 1,
      },
    ],
  },
  {
    _id: 'gcp4',
    group: {
      _id: 'grp-cyber',
      name: 'CyberSec FR',
      image: 'https://random.imagecdn.app/362/362',
      isPublic: true,
    },
    user: {
      _id: 'gu10',
      fullName: 'Sarah Chen',
      dp: 'https://random.imagecdn.app/380/380',
    },
    content:
      '🔥 Alerte recrutement !\n\nPoste : Pentester Senior\nEntreprise : SecLab (Remote)\nSalaire : 80 000 - 120 000 €\nExpérience : 3+ ans\n\nExigences : OSCP, tests web & réseau, rédaction de rapports\n\nDM ou commentez le lien de votre CV 👇',
    createdAt: new Date(Date.now() - 2 * 3600000),
    likes: 67,
    likeReactions: ['fas fa-thumbs-up', 'fas fa-heart'],
    commentsCount: 89,
    sharesCount: 34,
    comments: [
      {
        _id: 'gc7',
        user: {
          _id: 'gu11',
          fullName: 'Derek Morgan',
          dp: 'https://random.imagecdn.app/381/381',
        },
        text: 'Ouvert aux profils junior avec un bon portfolio de CTF ?',
        likes: 4,
        reactions: ['fas fa-thumbs-up'],
        createdAt: new Date(Date.now() - 1 * 3600000),
        replyCount: 1,
      },
      {
        _id: 'gc8',
        user: {
          _id: 'gu12',
          fullName: 'Michael Campbell',
          dp: 'https://random.imagecdn.app/382/382',
        },
        text: 'CV envoyé. 4 ans d’expérience en pentest web. Croisons les doigts ! 🤞',
        likes: 9,
        reactions: ['fas fa-thumbs-up', 'fas fa-heart'],
        createdAt: new Date(Date.now() - 45 * 60000),
        replyCount: 0,
      },
    ],
  },
];

export const chatsData: IChat[] = [
  {
    _id: 'ch1',
    user: {
      _id: 'cu1',
      fullName: 'Sarah Chen',
      dp: 'https://random.imagecdn.app/211/211',
      isOnline: true,
    },
    lastMessage: 'Où est-ce qu’on attaque le pentest de l’app ?',
    time: '2m',
    isUnread: true,
  },
  {
    _id: 'ch2',
    user: {
      _id: 'cu2',
      fullName: 'Emily Carter',
      dp: 'https://random.imagecdn.app/212/212',
      isOnline: true,
    },
    lastMessage: 'Toi : Haha ok, on lance le merge !',
    time: '45m',
    rightDp: 'https://random.imagecdn.app/500/200',
  },
  {
    _id: 'ch3',
    user: {
      _id: 'cu3',
      fullName: 'Tyler Brooks',
      dp: 'https://random.imagecdn.app/213/213',
    },
    lastMessage: 'Tyler a envoyé un message vocal.',
    time: '1h',
    isUnread: true,
  },
  {
    _id: 'ch4',
    user: {
      _id: 'cu4',
      fullName: 'Derek Morgan',
      dp: 'https://random.imagecdn.app/214/214',
      isOnline: true,
    },
    lastMessage: 'Toi : Merci pour l’aide, vraiment apprécié !',
    time: '3h',
  },
  {
    _id: 'ch5',
    user: {
      _id: 'cu5',
      fullName: 'Dev Squad 🚀',
      dp: 'https://random.imagecdn.app/380/380',
      isGroup: true,
    },
    lastMessage: 'Ryan : La review est finie, tu peux merger la PR.',
    time: '5h',
    isMuted: true,
  },
  {
    _id: 'ch6',
    user: {
      _id: 'cu6',
      fullName: 'Jason Foster',
      dp: 'https://random.imagecdn.app/215/215',
      isOnline: true,
    },
    lastMessage: 'Jason a envoyé une pièce jointe.',
    time: '7h',
    hasReply: true,
  },
  {
    _id: 'ch7',
    user: {
      _id: 'cu7',
      fullName: 'Michael Campbell',
      dp: 'https://random.imagecdn.app/216/216',
    },
    lastMessage: 'Toi : Je t’appelle après le stand-up.',
    time: '12h',
  },
  {
    _id: 'ch8',
    user: {
      _id: 'cu8',
      fullName: 'Bootcamp Dev 2026 🎓',
      dp: 'https://random.imagecdn.app/360/360',
      isGroup: true,
      isOnline: true,
    },
    lastMessage: 'Marcus : Quelqu’un sait quand tombent les résultats du hackathon ?',
    time: '1d',
    isMuted: true,
  },
  {
    _id: 'ch9',
    user: {
      _id: 'cu9',
      fullName: 'Russell Hansen',
      dp: 'https://random.imagecdn.app/219/219',
      isOnline: true,
    },
    lastMessage: 'On se retrouve demain pour la revue de code ?',
    time: '2d',
    hasReply: true,
  },
  {
    _id: 'ch10',
    user: {
      _id: 'cu10',
      fullName: 'Marcus Henderson',
      dp: 'https://random.imagecdn.app/217/217',
    },
    lastMessage: 'Toi : C’est noté, je t’envoie les fichiers maintenant.',
    time: '3d',
    hasFollowUp: true,
  },
  {
    _id: 'ch11',
    user: {
      _id: 'cu11',
      fullName: 'Nathan Hayes',
      dp: 'https://random.imagecdn.app/220/220',
    },
    lastMessage: 'Nathan a envoyé une photo de son setup.',
    time: '4d',
  },
  {
    _id: 'ch12',
    user: {
      _id: 'cu12',
      fullName: 'Syntax AI',
      dp: '',
      isAI: true,
    },
    lastMessage: 'Pose-moi n’importe quelle question de code ! ✨',
    time: '1w',
  },
];
